// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using NUnit.Framework;
using MediaMotion.Core.Services.FileSystem.Interfaces;
using MediaMotion.Core.Services.FileSystem;
using MediaMotion.Core.Models.FileManager.Interfaces;

namespace FileSystemTests {
	[TestFixture()]
	public class FileSystemTest {
		[Test()]
		public void getHomeDirectory() {
			FileSystem fileSystem = new FileSystem();
			Assert.AreNotEqual(null, fileSystem);
			IFolder homeFolder = fileSystem.GetHomeDirectory();
			Assert.AreNotEqual(null, homeFolder);
		}

		[Test()]
		public void GetWorkingDirectory() {
			Assert.Fail();
		}

		[Test()]
		public void ChangeDirectory() {
			Assert.Fail();
		}

		[Test()]
		public void GetDirectoryContent() {
			Assert.Fail();
		}

		[Test()]
		public void Copy() {
			Assert.Fail();
		}

		[Test()]
		public void Move() {
			Assert.Fail();
		}

		[Test()]
		public void Remove() {
			Assert.Fail();
		}

	}

}


