// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using NUnit.Framework;
using MediaMotion.Core.Services.FileSystem.Interfaces;
using MediaMotion.Core.Services.FileSystem;
using MediaMotion.Core.Models.FileManager.Interfaces;

[TestFixture()]
public class FileSystemTest
{
		[Test()]
		public void getHomeDirectory ()
		{
				IFileSystem fileSystem = new FileSystem ();
				Assert.AreNotEqual (null, fileSystem);
				IFolder homeFolder = fileSystem.GetHomeDirectory ();
				Assert.AreNotEqual (null, homeFolder);
		}
}


