// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using NUnit.Framework;

namespace FileManagerTests {
	[TestFixture()]
	public class AFileTest {
		[Test()]
		public void GetElementType() {
			Assert.Fail();
		}

		[Test()]
		public void GetFileType() {
			Assert.Fail();
		}

		[Test()]
		public void GetPath() {
			Assert.Fail();
		}

		[Test()]
		public void GetName() {
			Assert.Fail();
		}

		[Test()]
		public void GetExtension() {
			Assert.Fail();
		}

	}

}

